[package]
name = "miniflux-yt-plus"
version = "0.4.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.29", features = ["derive", "wrap_help"] }
miniflux_api = "0.7.2"
reqwest = "0.12.12"
tokio = { version = "1", features = ["full"] }
url = "2.5.4"
